---
version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    hostname: 'gitlab.fritz.box'
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.fritz.box'
        # Add any other gitlab.rb configuration here, each on its own line

    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - './app/config:/etc/gitlab'
      - './app/logs:/var/log/gitlab'
      - './app/data:/var/opt/gitlab'
    networks:
      - gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - ./runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab

networks:
  gitlab:
