---
- import_playbook: basics.yml
- hosts: all
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: create directory if they don't exist
      file:
        path: "{{ item }}"
        state: directory
        owner: pi
        group: pi
        mode: 0775
      loop:
        - /srv/container/gitlab
        - /srv/container/gitlab/app
        - /srv/container/gitlab/app/config
        - /srv/container/gitlab/app/data
        - /srv/container/gitlab/app/logs
        - /srv/container/gitlab/runner
        - /srv/container/gitlab/runner/config

    - name: copy docker-compose for gitlab
      copy:
        src: "../gitlab/docker-compose.yml"
        dest: /srv/container/gitlab/docker-compose.yml
        owner: pi
        group: pi
      register: gitlab_compose_file

    - name: "run docker-compose after changed"
      shell: cd /srv/container/gitlab/ && docker-compose up -d
      become: yes
      when: gitlab_compose_file.changed
