---
- hosts: all
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: create directory if they don't exist
      file:
        path: "{{ item }}"
        state: directory
        owner: pi
        group: pi
        mode: 0775
      loop:
        - /srv/container/minecraft
        - /srv/container/minecraft/data

    - name: copy docker-compose for minecraft
      copy:
        src: "../minecraft/docker-compose.yml"
        dest: /srv/container/minecraft/docker-compose.yml
        owner: pi
        group: pi
      register: compose_file

    - name: "run docker-compose after change"
      shell: cd /srv/container/minecraft/ && docker-compose up -d
      when: compose_file.changed
